gitcheck_paths:
- ./
gitcheck_pkgs:
- numpy
- scipy

globals:
  estimator: TT
  maps-path: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/rawmaps_250103/ #41227/
  experiment: 'ACT'
  freq: 90
  mlmax: 4000
  lmin: 600
  lmax: 3000
  filter-whitefwhm: 1.4
  filter-whiteamplitude: 12
  bias-hardening: False
  profile-hardening: False
  profile-path: /home/ia404/gitreps/so-lenspipe/data/tsz_profile5000.txt
  
root_dir: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/

stages:

  stage_filter_ACT_fskys:
    exec: python
    globals:
      - estimator
      - maps-path
      - experiment
      - mlmax
      - lmin
      - lmax
      - filter-whitefwhm
      - filter-whiteamplitude
      - bias-hardening
      - profile-hardening
      - profile-path
      - freq
    options:
      fgtypes: 'd9 d10 d12 DF_EB0 vand1'
      fskys: 'GAL060 GAL070 GAL080'
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:15:00'
    script: compute_biases.py
