gitcheck_paths:
- ./
gitcheck_pkgs:
- numpy
- scipy

globals:
  maps-path: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/rawmaps_250331/ #41227/ 250103
  mlmax: 4000
  fskys: GAL070
  lmin: 600
  lmax: 3000
  filter-whitefwhm: 1.4
  bias-hardening: False
  profile-hardening: False
  profile-path: /home/ia404/gitreps/so-lenspipe/data/tsz_profile5000.txt
  
root_dir: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/

stages:

  # stage_filter_SO_93_TT:
  #   exec: python
  #   globals:
  #     - maps-path
  #     - mlmax
  #     - lmin
  #     - lmax
  #     - filter-whitefwhm
  #     - bias-hardening
  #     - profile-hardening
  #     - profile-path
  #     - fskys
  #   options:
  #     experiment: 'SO'
  #     filter-whiteamplitude: 6
  #     fgtypes: 'DF_EB0 DF_EB'
  #     freq: 93
  #     estimator: TT
  #   parallel:
  #     nproc: 1
  #     threads: 14
  #     walltime: '00:10:00'
  #   script: compute_biases.py

  # stage_filter_SO_93_MV:
  #   exec: python
  #   globals:
  #     - maps-path
  #     - mlmax
  #     - lmin
  #     - lmax
  #     - filter-whitefwhm
  #     - bias-hardening
  #     - profile-hardening
  #     - profile-path
  #     - fskys
  #   options:
  #     experiment: 'SO'
  #     filter-whiteamplitude: 6
  #     fgtypes: 'DF_EB0 DF_EB'
  #     freq: 93
  #     estimator: MV
  #   parallel:
  #     nproc: 1
  #     threads: 56
  #     walltime: '00:10:00'
  #   script: compute_biases.py

  # stage_filter_SO_93_MVPOL:
  #   exec: python
  #   globals:
  #     - maps-path
  #     - mlmax
  #     - lmin
  #     - lmax
  #     - filter-whitefwhm
  #     - bias-hardening
  #     - profile-hardening
  #     - profile-path
  #     - fskys
  #   options:
  #     experiment: 'SO'
  #     filter-whiteamplitude: 6
  #     fgtypes: 'DF_EB0 DF_EB'
  #     freq: 93
  #     estimator: MVPOL
  #   parallel:
  #     nproc: 1
  #     threads: 14
  #     walltime: '00:10:00'
  #   script: compute_biases.py

  # stage_filter_SO_93_EB:
  #   exec: python
  #   globals:
  #     - maps-path
  #     - mlmax
  #     - lmin
  #     - lmax
  #     - filter-whitefwhm
  #     - bias-hardening
  #     - profile-hardening
  #     - profile-path
  #     - fskys
  #   options:
  #     experiment: 'SO'
  #     filter-whiteamplitude: 6
  #     fgtypes: 'DF_EB0 DF_EB'
  #     freq: 93
  #     estimator: EB
  #   parallel:
  #     nproc: 1
  #     threads: 14
  #     walltime: '00:10:00'
  #   script: compute_biases.py

  # stage_filter_ACT_90_EB:
  #   exec: python
  #   globals:
  #     - maps-path
  #     - mlmax
  #     - lmin
  #     - lmax
  #     - filter-whitefwhm
  #     - bias-hardening
  #     - profile-hardening
  #     - profile-path
  #     - fskys
  #   options:
  #     experiment: 'ACT'
  #     filter-whiteamplitude: 12
  #     fgtypes: 'DF_EB0 DF_EB'
  #     freq: 90
  #     estimator: EB
  #   parallel:
  #     nproc: 1
  #     threads: 14
  #     walltime: '00:10:00'
  #   script: compute_biases.py

  # stage_filter_ACT_90_MVPOL:
  #   exec: python
  #   globals:
  #     - maps-path
  #     - mlmax
  #     - lmin
  #     - lmax
  #     - filter-whitefwhm
  #     - bias-hardening
  #     - profile-hardening
  #     - profile-path
  #     - fskys
  #   options:
  #     experiment: 'ACT'
  #     filter-whiteamplitude: 12
  #     fgtypes: 'DF_EB0 DF_EB'
  #     freq: 90
  #     estimator: MVPOL
  #   parallel:
  #     nproc: 1
  #     threads: 14
  #     walltime: '00:10:00'
  #   script: compute_biases.py

  # stage_filter_ACT_90_TT:
  #   exec: python
  #   globals:
  #     - maps-path
  #     - mlmax
  #     - lmin
  #     - lmax
  #     - filter-whitefwhm
  #     - bias-hardening
  #     - profile-hardening
  #     - profile-path
  #     - fskys
  #   options:
  #     experiment: 'ACT'
  #     filter-whiteamplitude: 12
  #     fgtypes: 'DF_EB0 DF_EB'
  #     freq: 90
  #     estimator: TT
  #   parallel:
  #     nproc: 1
  #     threads: 14
  #     walltime: '00:10:00'
  #   script: compute_biases.py

  # stage_filter_ACT_90_MV:
  #   exec: python
  #   globals:
  #     - maps-path
  #     - mlmax
  #     - lmin
  #     - lmax
  #     - filter-whitefwhm
  #     - bias-hardening
  #     - profile-hardening
  #     - profile-path
  #     - fskys
  #   options:
  #     experiment: 'ACT'
  #     filter-whiteamplitude: 12
  #     fgtypes: 'DF_EB0 DF_EB'
  #     freq: 90
  #     estimator: MV
  #   parallel:
  #     nproc: 1
  #     threads: 28
  #     walltime: '00:10:00'
  #   script: compute_biases.py

  stage_filter_SO_145_TT:
    exec: python
    globals:
      - maps-path
      - mlmax
      - lmin
      - lmax
      - filter-whitefwhm
      - bias-hardening
      - profile-hardening
      - profile-path
      - fskys
    options:
      experiment: 'SO'
      filter-whiteamplitude: 6
      fgtypes: 'DF_EB0 DF_EB'
      freq: 145
      estimator: TT
    parallel:
      nproc: 1
      threads: 14
      walltime: '00:10:00'
    script: compute_biases.py

  stage_filter_SO_145_MV:
    exec: python
    globals:
      - maps-path
      - mlmax
      - lmin
      - lmax
      - filter-whitefwhm
      - bias-hardening
      - profile-hardening
      - profile-path
      - fskys
    options:
      experiment: 'SO'
      filter-whiteamplitude: 6
      fgtypes: 'DF_EB0 DF_EB'
      freq: 145
      estimator: MV
    parallel:
      nproc: 1
      threads: 56
      walltime: '00:10:00'
    script: compute_biases.py

  stage_filter_SO_145_MVPOL:
    exec: python
    globals:
      - maps-path
      - mlmax
      - lmin
      - lmax
      - filter-whitefwhm
      - bias-hardening
      - profile-hardening
      - profile-path
      - fskys
    options:
      experiment: 'SO'
      filter-whiteamplitude: 6
      fgtypes: 'DF_EB0 DF_EB'
      freq: 145
      estimator: MVPOL
    parallel:
      nproc: 1
      threads: 14
      walltime: '00:10:00'
    script: compute_biases.py

  stage_filter_SO_145_EB:
    exec: python
    globals:
      - maps-path
      - mlmax
      - lmin
      - lmax
      - filter-whitefwhm
      - bias-hardening
      - profile-hardening
      - profile-path
      - fskys
    options:
      experiment: 'SO'
      filter-whiteamplitude: 6
      fgtypes: 'DF_EB0 DF_EB'
      freq: 145
      estimator: EB
    parallel:
      nproc: 1
      threads: 14
      walltime: '00:10:00'
    script: compute_biases.py