gitcheck_paths:
- ./
gitcheck_pkgs:
- numpy
- scipy

globals:
  estimator: TT
  maps-path: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/rawmaps_250326_wcsSO/ #41227/
  experiment: 'SO'
  freq: 93
  mlmax: 4000
  fskys: GAL070
  lmax: 3000
  filter-whitefwhm: 1.4
  filter-whiteamplitude: 6
  bias-hardening: False
  profile-hardening: False
  profile-path: /home/ia404/gitreps/so-lenspipe/data/tsz_profile5000.txt
  
root_dir: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/

stages:

  stage_filter_SO_10:
    exec: python
    globals:
      - estimator
      - maps-path
      - experiment
      - mlmax
      - lmax
      - filter-whitefwhm
      - filter-whiteamplitude
      - bias-hardening
      - profile-hardening
      - profile-path
      - freq
      - fskys
    options:
      fgtypes: 'd9 d10 d12 DF_EB0 vand1'
      lmin: 10
    parallel:
      nproc: 1
      threads: 28
      walltime: '00:25:00'
    script: compute_biases.py

  stage_filter_SO_100:
    exec: python
    globals:
      - estimator
      - maps-path
      - experiment
      - mlmax
      - lmax
      - filter-whitefwhm
      - filter-whiteamplitude
      - bias-hardening
      - profile-hardening
      - profile-path
      - freq
      - fskys
    options:
      fgtypes: 'd9 d10 d12 DF_EB0 vand1'
      lmin: 100
    parallel:
      nproc: 1
      threads: 28
      walltime: '00:25:00'
    script: compute_biases.py

  stage_filter_SO_400:
    exec: python
    globals:
      - estimator
      - maps-path
      - experiment
      - mlmax
      - lmax
      - filter-whitefwhm
      - filter-whiteamplitude
      - bias-hardening
      - profile-hardening
      - profile-path
      - freq
      - fskys
    options:
      fgtypes: 'd9 d10 d12 DF_EB0 vand1'
      lmin: 400
    parallel:
      nproc: 1
      threads: 28
      walltime: '00:25:00'
    script: compute_biases.py

  stage_filter_SO_600:
    exec: python
    globals:
      - estimator
      - maps-path
      - experiment
      - mlmax
      - lmax
      - filter-whitefwhm
      - filter-whiteamplitude
      - bias-hardening
      - profile-hardening
      - profile-path
      - freq
      - fskys
    options:
      fgtypes: 'd9 d10 d12 DF_EB0 vand1'
      lmin: 600
    parallel:
      nproc: 1
      threads: 28
      walltime: '00:25:00'
    script: compute_biases.py