gitcheck_paths:
- ./
gitcheck_pkgs:
- numpy
- scipy
globals:
  config-name: act_dr6v4
  mask-type: dr6v4_20240919
  mask-subproduct: lensing_masks
  apodfact: '_d2_apo3deg'
  daynight: night
  width_ra: 15 # 35
  width_dec: 10 # 20
  
root_dir: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/

stages:

  stage_local_masks_GAL060:
    exec: python
    globals:
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - daynight
      - width_ra
      - width_dec
    options:
      skyfrac: GAL060
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:15:00'
    script: mbatch/local_dustbias/generate_local_masks.py

  stage_local_masks_GAL070:
    exec: python
    globals:
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - daynight
      - width_ra
      - width_dec
    options:
      skyfrac: GAL070
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:15:00'
    script: mbatch/local_dustbias/generate_local_masks.py

  stage_local_masks_GAL080:
    exec: python
    globals:
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - daynight
      - width_ra
      - width_dec
    options:
      skyfrac: GAL080
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:15:00'
    script: mbatch/local_dustbias/generate_local_masks.py


