gitcheck_paths:
- ./
gitcheck_pkgs:
- numpy
- scipy
globals:
  est: TT
  nside: 2048
  config-name: act_dr6v4
  mask-type: dr6v4_20240919
  mask-subproduct: lensing_masks
  apodfact: '_d2_apo3deg'
  daynight: night
  mlmax: 4000
  filter-whitefwhm: 1.4
  hpmask-fname: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/Planck/HFI_Mask_GalPlane-apo5_2048_R2.00.fits
  amplitudes-path: /home/ia404/gitreps/dustbias/mbatch/local_dustbias/amplitudes.pkl
  tilt-gauss: -0.8
  width_ra: 15 # 35
  width_dec: 10 # 20
  nsims-mf: 50
  
root_dir: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/

stages:

  stage_data_90:
    exec: python
    globals:
      - mlmax
      - nside
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - daynight
      - hpmask-fname
      - tilt-gauss
      - amplitudes-path
    options:
      dust-freq: 90
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:10:00'
    script: mbatch/local_dustbias/stage_generate_dustng_maps.py

  stage_data_150:
    exec: python
    globals:
      - mlmax
      - nside
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - daynight
      - hpmask-fname
      - tilt-gauss
      - amplitudes-path
    options:
      dust-freq: 150
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:10:00'
    script: mbatch/local_dustbias/stage_generate_dustng_maps.py

  stage_filter_ACT_600:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 600
      lmax: 3000
      filter-whiteamplitude: 12
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_SO_600:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 600
      lmax: 3000
      filter-whiteamplitude: 6
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py


  stage_filter_ACT_10:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 10
      lmax: 3000
      filter-whiteamplitude: 12
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_SO_10:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 10
      lmax: 3000
      filter-whiteamplitude: 6
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_ACT_1000:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 1000
      lmax: 3000
      filter-whiteamplitude: 12
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_SO_1000:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 1000
      lmax: 3000
      filter-whiteamplitude: 6
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_ACT_800:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 800
      lmax: 3000
      filter-whiteamplitude: 12
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_SO_800:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 800
      lmax: 3000
      filter-whiteamplitude: 6
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py


  stage_filter_ACT_100:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 100
      lmax: 3000
      filter-whiteamplitude: 12
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_SO_100:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 100
      lmax: 3000
      filter-whiteamplitude: 6
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_ACT_3500:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 600
      lmax: 3500
      filter-whiteamplitude: 12
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_filter_SO_3500:
    exec: python
    globals:
      - mlmax
      - filter-whitefwhm
    options:
      lmin: 600
      lmax: 3500
      filter-whiteamplitude: 6
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/local_dustbias/stage_compute_filters.py

  stage_local_masks_GAL060:
    exec: python
    globals:
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - daynight
      - width_ra
      - width_dec
    options:
      skyfrac: GAL060
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:15:00'
    script: mbatch/local_dustbias/generate_local_masks.py

  stage_local_masks_GAL070:
    exec: python
    globals:
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - daynight
      - width_ra
      - width_dec
    options:
      skyfrac: GAL070
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:15:00'
    script: mbatch/local_dustbias/generate_local_masks.py

  stage_local_masks_GAL080:
    exec: python
    globals:
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - daynight
      - width_ra
      - width_dec
    options:
      skyfrac: GAL080
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:15:00'
    script: mbatch/local_dustbias/generate_local_masks.py

  stage_auto_mf_gauss_90_GAL060_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: gauss
      lmax: 3000
      lmin: 600
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d9_90_GAL060_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: d9
      lmax: 3000
      lmin: 600
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d12_90_GAL060_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: d12
      lmax: 3000
      lmin: 600
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d9_90_GAL080_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: d9
      lmax: 3000
      lmin: 600
      skyfrac: GAL080
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '06:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_DF_90_GAL060_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: DF
      lmax: 3000
      lmin: 600
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_van_90_GAL060_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: van
      lmax: 3000
      lmin: 600
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d10_90_GAL060_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: d10
      lmax: 3000
      lmin: 600
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d9_90_GAL060_ACT_100_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: d9
      lmax: 3000
      lmin: 100
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d9_90_GAL060_ACT_10_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: d9
      lmax: 3000
      lmin: 10
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d9_90_GAL060_ACT_600_3500:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
    options:
      filter-whiteamplitude: 12
      dust-type: d9
      lmax: 3500
      lmin: 600
      skyfrac: GAL060
      dust-freq: 90
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:10:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py
