gitcheck_paths:
- ./
gitcheck_pkgs:
- numpy
- scipy
globals:
  est: TT
  nside: 2048
  config-name: act_dr6v4
  mask-type: dr6v4_20240919
  mask-subproduct: lensing_masks
  apodfact: '_d2_apo3deg'
  daynight: night
  mlmax: 4000
  filter-whitefwhm: 1.4
  filter-whiteamplitude: 12
  hpmask-fname: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/Planck/HFI_Mask_GalPlane-apo5_2048_R2.00.fits
  amplitudes-path: /home/ia404/gitreps/dustbias/mbatch/local_dustbias/amplitudes.pkl
  tilt-gauss: -0.8
  width_ra: 15 
  width_dec: 10
  nsims-mf: 50
  lmax: 3000
  lmin: 1000
  skyfrac: GAL070
  dust-freq: 90
  
root_dir: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs/

stages:

  stage_auto_mf_gauss_90_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
      - lmin
      - lmax
      - skyfrac
      - dust-freq
      - filter-whiteamplitude
    options:
      dust-type: gauss

    parallel:
      nproc: 8
      threads: 14
      walltime: '05:30:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d9_90_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
      - lmin
      - lmax
      - skyfrac
      - dust-freq
      - filter-whiteamplitude
    options:
      dust-type: d9
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:30:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_d10_90_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
      - lmin
      - lmax
      - skyfrac
      - dust-freq
      - filter-whiteamplitude
    options:
      dust-type: d10
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:30:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py


  stage_auto_mf_d12_90_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
      - lmin
      - lmax
      - skyfrac
      - dust-freq
      - filter-whiteamplitude
    options:
      dust-type: d12
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:30:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_DF_90_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
      - lmin
      - lmax
      - skyfrac
      - dust-freq
      - filter-whiteamplitude
    options:
      dust-type: DF
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:30:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

  stage_auto_mf_van_90_ACT_600_3000:
    exec: python
    globals:
      - est
      - filter-whitefwhm
      - mlmax
      - nsims-mf
      - width_ra
      - width_dec
      - lmin
      - lmax
      - skyfrac
      - dust-freq
      - filter-whiteamplitude
    options:
      dust-type: van
    parallel:
      nproc: 8
      threads: 14
      walltime: '05:30:00'
    script: mbatch/local_dustbias/stage_gauss_sims_measure_auto_with_mf.py

 