gitcheck_paths:
- ./
gitcheck_pkgs:
- numpy
- scipy
globals:
  est: TT
  nside: 2048
  config-name: act_dr6v4
  mask-type: wide_v4_20220316
  mask-subproduct: lensing_masks
  apodfact: 3dg
  mlmax: 4000
  lmax: 3000
  lmin: 600
  filter-whiteamplitude: 12
  filter-whitefwhm: 1.4
  dust-freq: 95
  skyfrac: GAL070
root_dir: /rds/project/dirac_vol5/rds-dirac-dp002/ia404/fgs

stages:

  stage_generate_fgs_dust_DF:
    exec: python
    globals:
      - nside
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - dust-freq
      - skyfrac
    options:
      dust-type: dust_DF
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/stage_generate_fgs.py

  stage_generate_fgs_dust_van:
    exec: python
    globals:
      - nside
      - config-name
      - mask-type
      - mask-subproduct
      - apodfact
      - dust-freq
      - skyfrac
    options:
      dust-type: dust_van
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/stage_generate_fgs.py

  # stage_generate_fgs_pysm_d1:
  #   exec: python
  #   globals:
  #     - nside
  #     - config-name
  #     - mask-type
  #     - mask-subproduct
  #     - apodfact
  #     - dust-freq
  #     - skyfrac
  #   options:
  #     dust-type: pysm_d1
  #   parallel:
  #     nproc: 1
  #     threads: 7
  #     walltime: '00:05:00'
  #   script: mbatch/stage_generate_fgs.py

  # stage_generate_fgs_pysm_d6:
  #   exec: python
  #   globals:
  #     - nside
  #     - config-name
  #     - mask-type
  #     - mask-subproduct
  #     - apodfact
  #     - dust-freq
  #     - skyfrac
  #   options:
  #     dust-type: pysm_d6
  #   parallel:
  #     nproc: 1
  #     threads: 7
  #     walltime: '00:05:00'
  #   script: mbatch/stage_generate_fgs.py

  # stage_generate_fgs_pysm_d10:
  #   exec: python
  #   globals:
  #     - nside
  #     - config-name
  #     - mask-type
  #     - mask-subproduct
  #     - apodfact
  #     - dust-freq
  #     - skyfrac
  #   options:
  #     dust-type: pysm_d10
  #   parallel:
  #     nproc: 1
  #     threads: 7
  #     walltime: '00:05:00'
  #   script: mbatch/stage_generate_fgs.py
  
  stage_filter:
    exec: python
    globals:
      - mlmax
      - lmax
      - lmin
      - filter-whiteamplitude
      - filter-whitefwhm
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/stage_compute_filters.py

  stage_auto_dust_DF:
    exec: python
    globals:
      - mlmax
      - lmax
      - lmin
      - filter-whiteamplitude
      - filter-whitefwhm
      - apodfact
      - mask-type
      - mask-subproduct
      - config-name
      - dust-freq
      - skyfrac
      - est
    options:
      dust-type: dust_DF
    depends:
      - stage_generate_fgs_dust_DF
      - stage_filter
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/stage_auto.py

  stage_auto_dust_van:
    exec: python
    globals:
      - mlmax
      - lmax
      - lmin
      - filter-whiteamplitude
      - filter-whitefwhm
      - apodfact
      - mask-type
      - mask-subproduct
      - config-name
      - dust-freq
      - skyfrac
      - est
    options:
      dust-type: dust_van
    depends:
      - stage_generate_fgs_dust_van
      - stage_filter
    parallel:
      nproc: 1
      threads: 7
      walltime: '00:05:00'
    script: mbatch/stage_auto.py

  # stage_auto_pysm_d1:
  #   exec: python
  #   globals:
  #     - mlmax
  #     - lmax
  #     - lmin
  #     - filter-whiteamplitude
  #     - filter-whitefwhm
  #     - apodfact
  #     - mask-type
  #     - mask-subproduct
  #     - config-name
  #     - dust-freq
  #     - skyfrac
  #     - est
  #   options:
  #     dust-type: pysm_d1
  #   depends:
  #     - stage_generate_fgs_pysm_d1
  #     - stage_filter
  #   parallel:
  #     nproc: 1
  #     threads: 7
  #     walltime: '00:05:00'
  #   script: mbatch/stage_auto.py

  # stage_auto_pysm_d6:
  #   exec: python
  #   globals:
  #     - mlmax
  #     - lmax
  #     - lmin
  #     - filter-whiteamplitude
  #     - filter-whitefwhm
  #     - apodfact
  #     - mask-type
  #     - mask-subproduct
  #     - config-name
  #     - dust-freq
  #     - skyfrac
  #     - est
  #   options:
  #     dust-type: pysm_d6
  #   depends:
  #     - stage_generate_fgs_pysm_d6
  #     - stage_filter
  #   parallel:
  #     nproc: 1
  #     threads: 7
  #     walltime: '00:05:00'
  #   script: mbatch/stage_auto.py
 
  # stage_auto_pysm_d10:
  #   exec: python
  #   globals:
  #     - mlmax
  #     - lmax
  #     - lmin
  #     - filter-whiteamplitude
  #     - filter-whitefwhm
  #     - apodfact
  #     - mask-type
  #     - mask-subproduct
  #     - config-name
  #     - dust-freq
  #     - skyfrac
  #     - est
  #   options:
  #     dust-type: pysm_d10
  #   depends:
  #     - stage_generate_fgs_pysm_d10
  #     - stage_filter
  #   parallel:
  #     nproc: 1
  #     threads: 7
  #     walltime: '00:05:00'
  #   script: mbatch/stage_auto.py 